from os import getenv

SECRET_KEY = getenv("SECRET_KEY")
DB_NAME = getenv("DB_NAME")
DB_USERNAME = getenv("DB_USERNAME")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_HOST = getenv("DB_HOST")
# BOOTSTRAP_SERVE_LOCAL = getenv("BOOTSTRAP_SERVE_LOCAL")
CLOUDINARY_CLOUD_NAME = 'djgxz5pxl'
CLOUDINARY_API_KEY = '779775775988384'
CLOUDINARY_API_SECRET = 'bBenabRT9xi69VEuJPA0EECJRCU'
